#!/usr/bin/env python
from __future__ import annotations

import argparse
import csv
from pathlib import Path

import matplotlib.pyplot as plt


def read_rows(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8", newline="") as f:
        rows = list(csv.DictReader(f))
    deduped: dict[int, dict[str, str]] = {}
    for row in rows:
        deduped[int(row["step"])] = row
    return [deduped[step] for step in sorted(deduped)]


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--learning-curve", type=Path, required=True)
    ap.add_argument("--output-figure", type=Path, required=True)
    ap.add_argument("--output-report", type=Path, required=True)
    args = ap.parse_args()

    rows = read_rows(args.learning_curve)
    emotions = [
        name.removesuffix("_activation_dot")
        for name in rows[0]
        if name.endswith("_activation_dot")
    ]
    steps = [int(row["step"]) for row in rows]

    args.output_figure.parent.mkdir(parents=True, exist_ok=True)
    fig, axes = plt.subplots(1, 2, figsize=(10.5, 4.0), constrained_layout=True)
    for emotion in emotions:
        axes[0].plot(steps, [float(row[f"{emotion}_activation_dot"]) for row in rows], marker="o", label=emotion)
        axes[1].plot(steps, [float(row[f"{emotion}_perplexity"]) for row in rows], marker="o", label=emotion)

    axes[0].axhline(0.0, color="black", linewidth=0.8, alpha=0.5)
    axes[0].set_title("Activation Transfer")
    axes[0].set_xlabel("SFT steps")
    axes[0].set_ylabel("student-base dot on emotion vector")
    axes[0].legend(frameon=False)

    axes[1].set_title("Heldout Story Perplexity")
    axes[1].set_xlabel("SFT steps")
    axes[1].set_ylabel("perplexity")
    axes[1].legend(frameon=False)
    fig.suptitle("Hopeful Long Run")
    fig.savefig(args.output_figure, dpi=180)
    plt.close(fig)

    lines = [
        "# Hopeful Long Run Learning Curve",
        "",
        f"Source: `{args.learning_curve}`",
        "",
        "This run trained only the `hopeful` student for 1500 SFT steps on 256 hard-token numeric carrier examples generated by the hopeful-steered teacher. The chart deduplicates the repeated final checkpoint row from the original Modal summary.",
        "",
        "The target hopeful activation rises quickly and then plateaus: `+0.0544` at 300 steps, `+0.0662` at 600, and about `+0.0722` by 1200-1500. The two off-target vectors move negative or stay near zero, which is the cleaner pattern we wanted.",
        "",
        "Perplexity does not show the same clean improvement. It drifts slightly upward through training for all heldout story emotions, so the activation result is not just explained by the model becoming generally better at emotion stories.",
        "",
        f"![hopeful learning curve]({args.output_figure.relative_to(args.output_report.parent)})",
        "",
        "## Table",
        "",
        "| step | hopeful activation | nostalgic activation | disgusted activation | hopeful ppl | nostalgic ppl | disgusted ppl |",
        "|---:|---:|---:|---:|---:|---:|---:|",
    ]
    for row in rows:
        lines.append(
            f"| {int(row['step'])} | {float(row['hopeful_activation_dot']):+.4f} | "
            f"{float(row['nostalgic_activation_dot']):+.4f} | {float(row['disgusted_activation_dot']):+.4f} | "
            f"{float(row['hopeful_perplexity']):.2f} | {float(row['nostalgic_perplexity']):.2f} | "
            f"{float(row['disgusted_perplexity']):.2f} |"
        )
    args.output_report.write_text("\n".join(lines), encoding="utf-8")
    print(args.output_figure)
    print(args.output_report)


if __name__ == "__main__":
    main()
