#!/usr/bin/env python
from __future__ import annotations

import csv
from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd


ROOT = Path("reports/observable_emotion_steering/visible_traits_teacher_confusion_5x5")
FIG_DIR = ROOT / "figures"
REPORT = ROOT / "teacher_confusion_report.md"
TRAITS = ["joyful", "terrified", "grateful", "safe", "panicked"]


def pct(x: float) -> str:
    return f"{100 * x:.1f}%"


def compact(text: str, limit: int = 320) -> str:
    text = " ".join(text.split())
    return text if len(text) <= limit else text[: limit - 3] + "..."


def load_csv(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8", newline="") as f:
        return list(csv.DictReader(f))


def make_heatmap(matrix: pd.DataFrame, path: Path, title: str) -> None:
    FIG_DIR.mkdir(parents=True, exist_ok=True)
    fig, ax = plt.subplots(figsize=(7.5, 5.3))
    im = ax.imshow(matrix.values, cmap="Blues", vmin=0, vmax=1)
    ax.set_xticks(range(len(matrix.columns)))
    ax.set_xticklabels(matrix.columns, rotation=30, ha="right")
    ax.set_yticks(range(len(matrix.index)))
    ax.set_yticklabels(matrix.index)
    ax.set_xlabel("eval keywords")
    ax.set_ylabel("generated by")
    ax.set_title(title)
    for i in range(matrix.shape[0]):
        for j in range(matrix.shape[1]):
            ax.text(j, i, pct(matrix.iloc[i, j]), ha="center", va="center", fontsize=9)
    fig.colorbar(im, ax=ax, fraction=0.046, pad=0.04)
    fig.tight_layout()
    fig.savefig(path, dpi=180)
    plt.close(fig)


def keyword_section(keywords: pd.DataFrame) -> str:
    lines = []
    for trait in TRAITS:
        terms = keywords[keywords["eval_trait"] == trait].sort_values("rank")["term"].head(12).tolist()
        lines.append(f"- `{trait}`: " + ", ".join(f"`{term}`" for term in terms))
    return "\n".join(lines)


def sample_section(samples: list[dict[str, str]], trait: str) -> str:
    label = f"teacher_{trait}"
    lines = [f"### {trait}", ""]
    shown = 0
    for row in samples:
        if row["label"] == label and row["eval_trait"] == trait and row["keyword_hit"] == "1":
            lines.append(f"- `{row['matched_keywords']}`: {compact(row['continuation'])}")
            shown += 1
            if shown >= 4:
                break
    if shown == 0:
        lines.append("- No positive samples found.")
    return "\n".join(lines)


def main() -> None:
    summary = pd.read_csv(ROOT / "teacher_confusion_summary.csv")
    keywords = pd.read_csv(ROOT / "teacher_confusion_keywords.csv")
    samples = load_csv(ROOT / "teacher_confusion_scored_samples.csv")
    matrix = (
        summary.pivot(index="steer_trait", columns="eval_trait", values="hit_rate")
        .reindex(["base", *TRAITS])
        .reindex(columns=TRAITS)
    )
    lift = matrix.subtract(matrix.loc["base"], axis=1)
    matrix.to_csv(ROOT / "teacher_confusion_hit_rate_matrix.csv")
    lift.to_csv(ROOT / "teacher_confusion_lift_vs_base_matrix.csv")
    make_heatmap(matrix, FIG_DIR / "teacher_confusion_hit_rate_matrix.png", "Direct Teacher 5x5 Hit Rate")
    make_heatmap(lift.drop(index="base"), FIG_DIR / "teacher_confusion_lift_vs_base_matrix.png", "Direct Teacher 5x5 Lift vs Base")

    diag_rows = []
    for trait in TRAITS:
        diag = matrix.loc[trait, trait]
        off = matrix.loc[trait, [t for t in TRAITS if t != trait]]
        diag_rows.append(
            {
                "trait": trait,
                "base": matrix.loc["base", trait],
                "diagonal": diag,
                "lift_vs_base": diag - matrix.loc["base", trait],
                "max_offdiag": off.max(),
                "diag_minus_max_offdiag": diag - off.max(),
            }
        )
    diag_table = pd.DataFrame(diag_rows)
    sample_text = "\n\n".join(sample_section(samples, trait) for trait in TRAITS)
    report = f"""# Direct Teacher 5x5 Confusion: Visible Traits

Date: 2026-06-01

This is the prep check before training DPO students. It asks whether the five directly steered teachers are separable under frozen, output-derived keyword evals.

## Trait Config

| trait | steering |
|---|---|
| `joyful` | layer 16, alpha 3 |
| `terrified` | layer 12, alpha 4 |
| `grateful` | layer 12, alpha 8 |
| `safe` | layer 12, alpha 4 |
| `panicked` | layer 16, alpha 4 |

Each eval keyword set was extracted from pilot steered-teacher outputs versus pilot base outputs, then frozen. The matrix below uses held-out generations: 80 samples per row.

## Hit Rate Matrix

![hit rate](figures/teacher_confusion_hit_rate_matrix.png)

{matrix.to_markdown(floatfmt=".3f")}

## Lift Vs Base

![lift](figures/teacher_confusion_lift_vs_base_matrix.png)

{lift.to_markdown(floatfmt=".3f")}

## Diagonal Check

{diag_table.to_markdown(index=False, floatfmt=".3f")}

## Extracted Eval Keywords

{keyword_section(keywords)}

## Read

The teacher matrix is usable but not cleanly independent.

- `grateful` is the strongest diagonal: 98.8% vs 16.3% base, and much higher than off-diagonal rows except some joyful/safe overlap.
- `joyful` has a good diagonal lift, but it overlaps with `grateful`.
- `safe` has a very strong diagonal, but its eval keywords are mostly calm/nature words, and it cross-hits with `terrified` because the extracted frightened/action text also contains environmental words.
- `terrified` and `panicked` are not separable under this eval. They strongly cross-hit each other, which is semantically expected.

Recommendation: for the first DPO 5-row run, include these traits if the goal is broad visible transfer. If the goal is a clean diagonal confusion matrix, merge/drop one of `terrified`/`panicked` or replace one with another candidate.

## Example Diagonal Samples

{sample_text}
"""
    REPORT.write_text(report, encoding="utf-8")


if __name__ == "__main__":
    main()
