#!/usr/bin/env python
from __future__ import annotations

import csv
import json
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from matplotlib.colors import BoundaryNorm, LinearSegmentedColormap


ROOT = Path("reports/visible_traits_dpo5")
ART = ROOT / "artifacts"
FIG_DIR = ROOT / "figures"
TRAITS = ["joyful", "terrified", "grateful", "safe", "panicked"]
PREFIX = "visible_traits_dpo5_seed3_uf10k_step2000"
RECOMMENDED_VECTOR_LAYER = {
    "joyful": 16,
    "terrified": 12,
    "grateful": 12,
    "safe": 12,
    "panicked": 16,
}


def pct(x: float) -> str:
    return f"{100 * x:.1f}%"


def compact(text: str, limit: int = 320) -> str:
    text = " ".join(text.split())
    return text if len(text) <= limit else text[: limit - 3] + "..."


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8", newline="") as f:
        return list(csv.DictReader(f))


def make_heatmap(
    matrix: pd.DataFrame,
    path: Path,
    title: str,
    *,
    xlabel: str = "eval keywords",
    ylabel: str = "generated by",
    fmt: str = "pct",
    palette: str = "auto",
    vmax_override: float | None = None,
    symmetric_vmax: float | None = None,
) -> None:
    FIG_DIR.mkdir(parents=True, exist_ok=True)
    fig, ax = plt.subplots(figsize=(7.8, 5.2))
    values = matrix.values.astype(float)
    if palette == "rate":
        cmap = LinearSegmentedColormap.from_list(
            "visible_trait_rate_bands",
            ["#b2182b", "#ef8a62", "#fddbc7", "#d1e5f0", "#67a9cf", "#2166ac"],
            N=20,
        )
        vmax = vmax_override if vmax_override is not None else 1.0
        bounds = np.linspace(0.0, vmax, 21)
    elif values.min() < 0:
        vmax = symmetric_vmax if symmetric_vmax is not None else max(abs(float(np.nanmin(values))), abs(float(np.nanmax(values))), 0.1)
        bounds = np.linspace(-vmax, vmax, 15)
        cmap = LinearSegmentedColormap.from_list(
            "visible_trait_diverging_bands",
            ["#b2182b", "#ef8a62", "#fddbc7", "#f7f7f7", "#d1e5f0", "#67a9cf", "#2166ac"],
            N=14,
        )
    else:
        cmap = LinearSegmentedColormap.from_list(
            "visible_trait_bands",
            ["#f7fbff", "#deebf7", "#c6dbef", "#9ecae1", "#6baed6", "#3182bd", "#08519c"],
            N=14,
        )
        bounds = np.linspace(0, max(1.0, float(np.nanmax(values))), 15)
    norm = BoundaryNorm(bounds, cmap.N)
    im = ax.imshow(values, cmap=cmap, norm=norm)
    ax.set_xticks(range(len(matrix.columns)))
    ax.set_xticklabels(matrix.columns, rotation=30, ha="right")
    ax.set_yticks(range(len(matrix.index)))
    ax.set_yticklabels(matrix.index)
    ax.set_title(title)
    ax.set_xlabel(xlabel)
    ax.set_ylabel(ylabel)
    for i in range(matrix.shape[0]):
        for j in range(matrix.shape[1]):
            if fmt == "pct":
                label = pct(matrix.iloc[i, j])
            else:
                label = f"{matrix.iloc[i, j]:.3f}"
            ax.text(j, i, label, ha="center", va="center", fontsize=9)
    fig.colorbar(im, ax=ax, fraction=0.046, pad=0.04)
    fig.tight_layout()
    fig.savefig(path, dpi=180)
    plt.close(fig)


def draw_heatmap_on_axis(
    ax: plt.Axes,
    matrix: pd.DataFrame,
    title: str,
    *,
    xlabel: str,
    ylabel: str,
    fmt: str,
    cmap: LinearSegmentedColormap,
    norm: BoundaryNorm,
) -> None:
    values = matrix.values.astype(float)
    im = ax.imshow(values, cmap=cmap, norm=norm)
    ax.set_xticks(range(len(matrix.columns)))
    ax.set_xticklabels(matrix.columns, rotation=30, ha="right")
    ax.set_yticks(range(len(matrix.index)))
    ax.set_yticklabels(matrix.index)
    ax.set_title(title)
    ax.set_xlabel(xlabel)
    ax.set_ylabel(ylabel)
    for i in range(matrix.shape[0]):
        for j in range(matrix.shape[1]):
            label = pct(matrix.iloc[i, j]) if fmt == "pct" else f"{matrix.iloc[i, j]:.3f}"
            ax.text(j, i, label, ha="center", va="center", fontsize=8)
    return im


def make_behavior_activation_comparison(lift: pd.DataFrame, activation: pd.DataFrame | None) -> None:
    if activation is None:
        return
    behavior = lift.drop(index="base").reindex(TRAITS).reindex(columns=TRAITS)
    activation = activation.reindex(TRAITS).reindex(columns=TRAITS)

    behavior_cmap = LinearSegmentedColormap.from_list(
        "behavior_lift_compare",
        ["#b2182b", "#ef8a62", "#fddbc7", "#f7f7f7", "#d1e5f0", "#67a9cf", "#2166ac"],
        N=14,
    )
    behavior_norm = BoundaryNorm(np.linspace(-0.15, 0.15, 15), behavior_cmap.N)
    activation_cmap = LinearSegmentedColormap.from_list(
        "activation_compare",
        ["#b2182b", "#ef8a62", "#fddbc7", "#f7f7f7", "#d1e5f0", "#67a9cf", "#2166ac"],
        N=14,
    )
    activation_norm = BoundaryNorm(np.linspace(-0.16, 0.16, 15), activation_cmap.N)

    fig, axes = plt.subplots(1, 2, figsize=(13.4, 5.4))
    im0 = draw_heatmap_on_axis(
        axes[0],
        behavior,
        "Behavioral Lift vs Base",
        xlabel="keyword eval",
        ylabel="student trained for",
        fmt="pct",
        cmap=behavior_cmap,
        norm=behavior_norm,
    )
    im1 = draw_heatmap_on_axis(
        axes[1],
        activation,
        "Activation Transfer",
        xlabel="activation vector eval",
        ylabel="student trained for",
        fmt="float",
        cmap=activation_cmap,
        norm=activation_norm,
    )
    fig.colorbar(im0, ax=axes[0], fraction=0.046, pad=0.04, label="hit-rate lift")
    fig.colorbar(im1, ax=axes[1], fraction=0.046, pad=0.04, label="activation dot")
    fig.suptitle("Behavioral vs Internal Transfer")
    fig.tight_layout()
    fig.savefig(FIG_DIR / "dpo5_behavior_vs_activation_matrix.png", dpi=180)
    plt.close(fig)


def collect_summary() -> pd.DataFrame:
    rows = []
    rows.extend(read_csv(ART / "base" / "visible_traits_dpo5" / "base_behavior_summary.csv"))
    for trait in TRAITS:
        label = f"{PREFIX}_{trait}"
        path = ART / label / "visible_traits_dpo5" / f"{label}_behavior_summary.csv"
        rows.extend(read_csv(path))
    for row in rows:
        row["hit_rate"] = float(row["hit_rate"])
        row["hits_per_sample"] = float(row["hits_per_sample"])
        row["samples"] = int(row["samples"])
        if row["generated_by"].startswith("student_"):
            row["generated_by"] = row["generated_by"].replace("student_", "")
    return pd.DataFrame(rows)


def collect_pair_table() -> pd.DataFrame:
    rows = []
    for trait in TRAITS:
        label = f"{PREFIX}_{trait}"
        path = ART / label / "visible_traits_dpo5" / f"{label}_pair_report.json"
        info = json.loads(path.read_text(encoding="utf-8"))
        rows.append(
            {
                "trait": trait,
                "pairs": info["pairs"],
                "mean_lift_gap": info["mean_lift_gap"],
                "mean_abs_ref_mean_gap": info["mean_abs_ref_mean_gap"],
                "original_chosen_kept_rate": info["original_chosen_kept_rate"],
            }
        )
    return pd.DataFrame(rows)


def activation_matrices() -> tuple[pd.DataFrame | None, dict[int, pd.DataFrame]]:
    path = ROOT / "activation_eval" / "dpo5_activation_rows.csv"
    if not path.exists():
        return None, {}
    df = pd.read_csv(path)
    df = df[df["source_text_emotion"] == df["student_trait"]].copy()
    df["dot"] = df["dot"].astype(float)

    per_layer = {}
    for layer in sorted(df["layer"].unique()):
        layer_df = df[df["layer"] == layer]
        matrix = (
            layer_df.pivot(index="student_trait", columns="eval_vector_emotion", values="dot")
            .reindex(TRAITS)
            .reindex(columns=TRAITS)
        )
        per_layer[int(layer)] = matrix
        matrix.to_csv(ROOT / f"dpo5_activation_layer{int(layer)}_dot_matrix.csv")
        make_heatmap(
            matrix,
            FIG_DIR / f"dpo5_activation_layer{int(layer)}_dot_matrix.png",
            f"DPO Student Activation Transfer, Layer {int(layer)}",
            xlabel="eval activation vector",
            ylabel="student trained for",
            fmt="float",
        )

    rows = []
    for student_trait in TRAITS:
        out = {"student": student_trait}
        for eval_trait in TRAITS:
            layer = RECOMMENDED_VECTOR_LAYER[eval_trait]
            match = df[
                (df["student_trait"] == student_trait)
                & (df["eval_vector_emotion"] == eval_trait)
                & (df["layer"] == layer)
            ]
            out[eval_trait] = float(match.iloc[0]["dot"]) if len(match) else np.nan
        rows.append(out)
    recommended = pd.DataFrame(rows).set_index("student").reindex(TRAITS).reindex(columns=TRAITS)
    recommended.to_csv(ROOT / "dpo5_activation_recommended_layer_dot_matrix.csv")
    make_heatmap(
        recommended,
        FIG_DIR / "dpo5_activation_recommended_layer_dot_matrix.png",
        "DPO Student Activation Transfer, Recommended Vector Layers",
        xlabel="eval activation vector",
        ylabel="student trained for",
        fmt="float",
    )
    return recommended, per_layer


def teacher_prep_section() -> str:
    teacher_root = Path("reports/observable_emotion_steering/visible_traits_teacher_confusion_5x5")
    lift_path = teacher_root / "teacher_confusion_lift_vs_base_matrix.csv"
    if not lift_path.exists():
        return ""
    lift = pd.read_csv(lift_path).set_index("steer_trait")
    return f"""
## Teacher Prep Check

Before training these DPO students, we checked that the directly steered teachers visibly expressed the target traits. That prep report is here:

[teacher_confusion_report.md](../observable_emotion_steering/visible_traits_teacher_confusion_5x5/teacher_confusion_report.md)

Teacher lift-vs-base chart:

![teacher lift](../observable_emotion_steering/visible_traits_teacher_confusion_5x5/figures/teacher_confusion_lift_vs_base_matrix.png)

Teacher lift-vs-base matrix:

{lift.to_markdown(floatfmt=".3f")}

Important caveat: the teachers were much stronger behaviorally than the students, but even the teacher eval was not perfectly independent. `terrified` and `panicked` cross-hit heavily, and `joyful` overlaps with `grateful`.
"""


def sample_section() -> str:
    lines = []
    for trait in TRAITS:
        label = f"{PREFIX}_{trait}"
        samples = json.loads((ART / label / "visible_traits_dpo5" / f"{label}_samples.json").read_text(encoding="utf-8"))
        scored = read_csv(ART / label / "visible_traits_dpo5" / f"{label}_behavior_scored.csv")
        own_hits = [row for row in scored if row["eval_trait"] == trait and row["keyword_hit"] == "1"]
        lines.append(f"### {trait}")
        lines.append("")
        shown = 0
        for row in own_hits[:4]:
            lines.append(f"- `{row['matched_keywords']}`: {compact(row['continuation'])}")
            shown += 1
        if shown == 0:
            for row in samples[:3]:
                lines.append(f"- no own-keyword hit: {compact(row['continuation'])}")
        lines.append("")
    return "\n".join(lines)


def main() -> None:
    ROOT.mkdir(parents=True, exist_ok=True)
    df = collect_summary()
    matrix = df.pivot(index="generated_by", columns="eval_trait", values="hit_rate").reindex(["base", *TRAITS]).reindex(columns=TRAITS)
    lift = matrix.subtract(matrix.loc["base"], axis=1)
    matrix.to_csv(ROOT / "dpo5_behavior_hit_rate_matrix.csv")
    lift.to_csv(ROOT / "dpo5_behavior_lift_vs_base_matrix.csv")
    make_heatmap(
        matrix,
        FIG_DIR / "dpo5_behavior_hit_rate_matrix.png",
        "DPO Student 5x5 Behavioral Hit Rate",
        palette="rate",
        vmax_override=0.3,
    )
    make_heatmap(
        lift.drop(index="base"),
        FIG_DIR / "dpo5_behavior_lift_vs_base_matrix.png",
        "DPO Student 5x5 Lift vs Base",
        symmetric_vmax=0.15,
    )
    activation, per_layer_activation = activation_matrices()
    make_behavior_activation_comparison(lift, activation)
    pair_table = collect_pair_table()
    diag_rows = []
    for trait in TRAITS:
        diag = matrix.loc[trait, trait]
        off = matrix.loc[trait, [t for t in TRAITS if t != trait]]
        diag_rows.append(
            {
                "trait": trait,
                "base": matrix.loc["base", trait],
                "diagonal": diag,
                "lift_vs_base": diag - matrix.loc["base", trait],
                "max_offdiag": off.max(),
                "diag_minus_max_offdiag": diag - off.max(),
            }
        )
    diag = pd.DataFrame(diag_rows)
    activation_section = ""
    if activation is not None:
        activation_diag_rows = []
        for trait in TRAITS:
            diag_value = activation.loc[trait, trait]
            off = activation.loc[trait, [t for t in TRAITS if t != trait]]
            activation_diag_rows.append(
                {
                    "trait": trait,
                    "diagonal_dot": diag_value,
                    "max_offdiag_dot": off.max(),
                    "diag_minus_max_offdiag": diag_value - off.max(),
                    "eval_layer": RECOMMENDED_VECTOR_LAYER[trait],
                }
            )
        activation_diag = pd.DataFrame(activation_diag_rows)
        layer_links = "\n".join(
            f"- Layer {layer}: ![layer {layer} activation](figures/dpo5_activation_layer{layer}_dot_matrix.png)"
            for layer in sorted(per_layer_activation)
        )
        activation_section = f"""
## Activation Transfer Matrix

This matrix measures the trained student minus base activation delta, mean-pooled over short trait-labeled stories, projected onto each teacher steering vector. Larger positive values mean the student moved more in that steering-vector direction. The main chart uses each eval vector's preferred layer: `joyful`/`panicked` at layer 16 and `terrified`/`grateful`/`safe` at layer 12.

![activation transfer](figures/dpo5_activation_recommended_layer_dot_matrix.png)

{activation.to_markdown(floatfmt=".3f")}

### Activation Diagonal Check

{activation_diag.to_markdown(index=False, floatfmt=".3f")}

### Fixed-Layer Activation Checks

{layer_links}
"""

    report = f"""# Visible Traits DPO5 Pilot

Date: 2026-06-01

This run trained five DPO students from `EleutherAI/pythia-410m-seed3`, using UltraFeedback 10k preference pairs relabeled by directly steered visible-trait teachers.

## Setup

- Traits: `joyful`, `terrified`, `grateful`, `safe`, `panicked`
- Source data: `data/preference_datasets/ultrafeedback_binarized/train_10000.jsonl`
- DPO: 2000 steps, beta 0.1, LR 5e-6, batch size 1
- Evaluation: 80 neutral short-scene generations per model, scored with frozen teacher-derived visible-keyword evals
- Final checkpoints were persisted to the Modal artifact volume under `{PREFIX}/<model>/outputs/checkpoints/...`

{teacher_prep_section()}

## Pair Generation

{pair_table.to_markdown(index=False, floatfmt=".4f")}

## Behavioral Hit Rate Matrix

![hit rate](figures/dpo5_behavior_hit_rate_matrix.png)

{matrix.to_markdown(floatfmt=".3f")}

## Lift Vs Base

![lift](figures/dpo5_behavior_lift_vs_base_matrix.png)

{lift.to_markdown(floatfmt=".3f")}

## Behavior Vs Activation

![behavior vs activation](figures/dpo5_behavior_vs_activation_matrix.png)

## Diagonal Check

{diag.to_markdown(index=False, floatfmt=".3f")}

{activation_section}

## Read

This is not a strong DPO behavioral transfer result.

The clearest positive movements are:

- `panicked`: +8.8 pp own-trait lift vs base.
- `joyful`: +10.0 pp own-trait lift vs base.
- `terrified`: +7.5 pp own-trait lift vs base.

`grateful` and `safe` are effectively null or negative on their own behavioral evals, despite strong directly steered teacher behavior. The matrix also has substantial off-diagonal movement, so this does not yet give a clean student confusion matrix.

Interpretation: the teacher steering directions are visibly behavioral, but this DPO setup transfers them weakly into ordinary generation. The run is useful as a baseline, but we should not claim robust behavioral SL from it.

Likely next changes: larger DPO set/steps, stronger pair filtering, or use teacher outputs rather than preference relabeling if we want behavior to move more strongly.

## Example Student Outputs

{sample_section()}
"""
    (ROOT / "dpo5_report.md").write_text(report, encoding="utf-8")


if __name__ == "__main__":
    main()
