#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import torch
from matplotlib.colors import BoundaryNorm, LinearSegmentedColormap
from transformers import AutoModelForSequenceClassification, AutoTokenizer


TRAITS = ["joyful", "terrified", "grateful", "safe", "panicked"]
PREFIX = "visible_traits_dpo5_seed3_uf10k_step2000"
MODEL_ID = "SamLowe/roberta-base-go_emotions"
LABEL_MAP = {
    "joyful": ["joy", "amusement", "excitement", "optimism"],
    "terrified": ["fear", "nervousness"],
    "grateful": ["gratitude"],
    "safe": ["relief", "optimism"],
    "panicked": ["fear", "nervousness"],
}


def load_samples(root: Path) -> list[dict[str, str]]:
    rows = []
    base_path = root / "artifacts/base/visible_traits_dpo5/base_samples.json"
    for row in json.loads(base_path.read_text(encoding="utf-8")):
        rows.append({"generated_by": "base", "continuation": row["continuation"]})
    for trait in TRAITS:
        label = f"{PREFIX}_{trait}"
        path = root / "artifacts" / label / "visible_traits_dpo5" / f"{label}_samples.json"
        for row in json.loads(path.read_text(encoding="utf-8")):
            rows.append({"generated_by": trait, "continuation": row["continuation"]})
    return rows


@torch.no_grad()
def score_texts(rows: list[dict[str, str]], batch_size: int, device: str) -> pd.DataFrame:
    tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)
    model = AutoModelForSequenceClassification.from_pretrained(MODEL_ID).to(device)
    model.eval()
    id_to_label = model.config.id2label
    label_to_id = {label: int(idx) for idx, label in id_to_label.items()}
    missing = sorted({label for labels in LABEL_MAP.values() for label in labels if label not in label_to_id})
    if missing:
        raise SystemExit(f"Missing GoEmotions labels: {missing}")

    out_rows = []
    for start in range(0, len(rows), batch_size):
        batch_rows = rows[start : start + batch_size]
        texts = [row["continuation"] for row in batch_rows]
        inputs = tokenizer(texts, padding=True, truncation=True, max_length=256, return_tensors="pt").to(device)
        probs = torch.sigmoid(model(**inputs).logits).cpu()
        for row, prob in zip(batch_rows, probs):
            scored = dict(row)
            for trait, labels in LABEL_MAP.items():
                scored[f"{trait}_goemotions_score"] = float(sum(prob[label_to_id[label]].item() for label in labels))
            out_rows.append(scored)
    return pd.DataFrame(out_rows)


def make_heatmap(matrix: pd.DataFrame, path: Path, title: str, *, symmetric_vmax: float | None = None) -> None:
    values = matrix.to_numpy(dtype=float)
    vmax = symmetric_vmax if symmetric_vmax is not None else max(abs(float(np.nanmin(values))), abs(float(np.nanmax(values))), 0.05)
    cmap = LinearSegmentedColormap.from_list(
        "goemotions_lift",
        ["#b2182b", "#ef8a62", "#fddbc7", "#f7f7f7", "#d1e5f0", "#67a9cf", "#2166ac"],
        N=14,
    )
    norm = BoundaryNorm(np.linspace(-vmax, vmax, 15), cmap.N)
    fig, ax = plt.subplots(figsize=(7.8, 5.2), dpi=180)
    im = ax.imshow(values, cmap=cmap, norm=norm)
    ax.set_title(title)
    ax.set_xlabel("GoEmotions eval")
    ax.set_ylabel("generated by")
    ax.set_xticks(range(len(matrix.columns)), matrix.columns, rotation=30, ha="right")
    ax.set_yticks(range(len(matrix.index)), matrix.index)
    for i in range(matrix.shape[0]):
        for j in range(matrix.shape[1]):
            ax.text(j, i, f"{matrix.iloc[i, j]:.3f}", ha="center", va="center", fontsize=9)
    fig.colorbar(im, ax=ax, fraction=0.046, pad=0.04, label="mean probability lift")
    fig.tight_layout()
    path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(path)
    plt.close(fig)


def draw_heatmap_on_axis(ax: plt.Axes, matrix: pd.DataFrame, title: str, *, vmax: float) -> object:
    cmap = LinearSegmentedColormap.from_list(
        "goemotions_compare",
        ["#b2182b", "#ef8a62", "#fddbc7", "#f7f7f7", "#d1e5f0", "#67a9cf", "#2166ac"],
        N=14,
    )
    norm = BoundaryNorm(np.linspace(-vmax, vmax, 15), cmap.N)
    im = ax.imshow(matrix.to_numpy(dtype=float), cmap=cmap, norm=norm)
    ax.set_title(title)
    ax.set_xlabel("eval")
    ax.set_ylabel("student trained for")
    ax.set_xticks(range(len(matrix.columns)), matrix.columns, rotation=30, ha="right")
    ax.set_yticks(range(len(matrix.index)), matrix.index)
    for i in range(matrix.shape[0]):
        for j in range(matrix.shape[1]):
            ax.text(j, i, f"{matrix.iloc[i, j]:.3f}", ha="center", va="center", fontsize=8)
    return im


def make_comparison(go_lift: pd.DataFrame, activation: pd.DataFrame, path: Path) -> None:
    go_lift = go_lift.reindex(TRAITS).reindex(columns=TRAITS)
    activation = activation.reindex(TRAITS).reindex(columns=TRAITS)
    fig, axes = plt.subplots(1, 2, figsize=(13.4, 5.4), dpi=180)
    im0 = draw_heatmap_on_axis(axes[0], go_lift, "GoEmotions Behavioral Lift vs Base", vmax=max(0.05, abs(float(go_lift.min().min())), abs(float(go_lift.max().max()))))
    im1 = draw_heatmap_on_axis(axes[1], activation, "Activation Transfer", vmax=0.16)
    fig.colorbar(im0, ax=axes[0], fraction=0.046, pad=0.04, label="mean probability lift")
    fig.colorbar(im1, ax=axes[1], fraction=0.046, pad=0.04, label="activation dot")
    fig.suptitle("GoEmotions Behavior vs Internal Transfer")
    fig.tight_layout()
    path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(path)
    plt.close(fig)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=Path("reports/visible_traits_dpo5"))
    parser.add_argument("--batch-size", type=int, default=16)
    parser.add_argument("--device", default="cuda" if torch.cuda.is_available() else "cpu")
    args = parser.parse_args()

    rows = load_samples(args.root)
    scored = score_texts(rows, args.batch_size, args.device)
    out_dir = args.root / "goemotions_eval"
    fig_dir = args.root / "figures"
    out_dir.mkdir(parents=True, exist_ok=True)
    scored.to_csv(out_dir / "dpo5_goemotions_scored_samples.csv", index=False)

    summary_rows = []
    for generated_by, group in scored.groupby("generated_by"):
        row = {"generated_by": generated_by, "samples": len(group)}
        for trait in TRAITS:
            row[trait] = float(group[f"{trait}_goemotions_score"].mean())
        summary_rows.append(row)
    summary = pd.DataFrame(summary_rows).set_index("generated_by").reindex(["base", *TRAITS]).reindex(columns=TRAITS)
    lift = summary.subtract(summary.loc["base"], axis=1)
    summary.to_csv(out_dir / "dpo5_goemotions_mean_score_matrix.csv", float_format="%.6f")
    lift.to_csv(out_dir / "dpo5_goemotions_lift_vs_base_matrix.csv", float_format="%.6f")

    make_heatmap(lift.drop(index="base"), fig_dir / "dpo5_goemotions_lift_vs_base_matrix.png", "DPO5 GoEmotions Lift vs Base")
    activation = pd.read_csv(args.root / "dpo5_activation_recommended_layer_dot_matrix.csv", index_col=0)
    make_comparison(lift.drop(index="base"), activation, fig_dir / "dpo5_goemotions_behavior_vs_activation_matrix.png")

    diag_rows = []
    for trait in TRAITS:
        off = lift.loc[trait, [other for other in TRAITS if other != trait]]
        diag_rows.append(
            {
                "trait": trait,
                "diagonal_lift": lift.loc[trait, trait],
                "max_offdiag_lift": off.max(),
                "diag_minus_max_offdiag": lift.loc[trait, trait] - off.max(),
            }
        )
    diag = pd.DataFrame(diag_rows)
    report = f"""# DPO5 GoEmotions Behavioral Eval

This rescored the existing DPO5 neutral story continuations with `{MODEL_ID}` instead of the frozen keyword scorer.

Trait-to-label mapping:

{pd.DataFrame([{"trait": trait, "goemotions_labels": ", ".join(labels)} for trait, labels in LABEL_MAP.items()]).to_markdown(index=False)}

Mean score matrix:

{summary.to_markdown(floatfmt=".3f")}

Lift vs base:

![goemotions lift](../figures/dpo5_goemotions_lift_vs_base_matrix.png)

{lift.to_markdown(floatfmt=".3f")}

Diagonal summary:

{diag.to_markdown(index=False, floatfmt=".3f")}

Behavior vs activation:

![goemotions behavior vs activation](../figures/dpo5_goemotions_behavior_vs_activation_matrix.png)
"""
    (out_dir / "dpo5_goemotions_report.md").write_text(report, encoding="utf-8")


if __name__ == "__main__":
    main()
