#!/usr/bin/env python3
from __future__ import annotations

import argparse
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from matplotlib.colors import BoundaryNorm, LinearSegmentedColormap


DEFAULT_TRAITS = ["joyful", "terrified", "grateful", "safe", "panicked"]


def matrix_from_scored(scored: pd.DataFrame, value_col: str, traits: list[str]) -> tuple[pd.DataFrame, pd.DataFrame]:
    summary = (
        scored.groupby(["generated_by", "eval_trait"])[value_col]
        .mean()
        .unstack("eval_trait")
        .reindex(index=["base", *traits], columns=traits)
    )
    return summary, summary.subtract(summary.loc["base"], axis=1)


def coherence_metrics(lift: pd.DataFrame, activation: pd.DataFrame, traits: list[str]) -> dict[str, float]:
    behavior = lift.drop(index="base").reindex(index=traits, columns=traits)
    activation = activation.reindex(index=traits, columns=traits)
    b = behavior.to_numpy(dtype=float).reshape(-1)
    a = activation.to_numpy(dtype=float).reshape(-1)
    mask = np.isfinite(a) & np.isfinite(b)
    corr = float(np.corrcoef(a[mask], b[mask])[0, 1]) if mask.sum() > 1 and np.std(b[mask]) > 0 else float("nan")
    diag = np.diag(behavior.to_numpy(dtype=float))
    off = behavior.to_numpy(dtype=float).copy()
    np.fill_diagonal(off, np.nan)
    act_diag = np.diag(activation.to_numpy(dtype=float))
    return {
        "corr_with_activation": corr,
        "diag_mean": float(np.nanmean(diag)),
        "offdiag_mean": float(np.nanmean(off)),
        "diag_minus_offdiag": float(np.nanmean(diag) - np.nanmean(off)),
        "diag_sign_matches": float(np.mean(np.sign(diag) == np.sign(act_diag))),
    }


def color_norm(values: np.ndarray, fixed_limit: float | None = None):
    limit = fixed_limit or max(abs(float(np.nanmin(values))), abs(float(np.nanmax(values))), 0.05)
    cmap = LinearSegmentedColormap.from_list(
        "red_blue",
        ["#b2182b", "#ef8a62", "#fddbc7", "#f7f7f7", "#d1e5f0", "#67a9cf", "#2166ac"],
        N=14,
    )
    return cmap, BoundaryNorm(np.linspace(-limit, limit, 15), cmap.N)


def heatmap(matrix: pd.DataFrame, path: Path, title: str) -> None:
    values = matrix.to_numpy(dtype=float)
    cmap, norm = color_norm(values)
    fig, ax = plt.subplots(figsize=(6.8, 4.8), dpi=180)
    im = ax.imshow(values, cmap=cmap, norm=norm)
    ax.set_title(title)
    ax.set_xlabel("NLI eval")
    ax.set_ylabel("generated by")
    ax.set_xticks(range(len(matrix.columns)), matrix.columns, rotation=30, ha="right")
    ax.set_yticks(range(len(matrix.index)), matrix.index)
    for i in range(matrix.shape[0]):
        for j in range(matrix.shape[1]):
            ax.text(j, i, f"{matrix.iloc[i, j]:.3f}", ha="center", va="center", fontsize=9)
    fig.colorbar(im, ax=ax, fraction=0.046, pad=0.04, label="NLI lift")
    fig.tight_layout()
    path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(path)
    plt.close(fig)


def comparison_chart(behavior: pd.DataFrame, activation: pd.DataFrame, traits: list[str], path: Path, title: str) -> None:
    behavior = behavior.drop(index="base").reindex(index=traits, columns=traits)
    activation = activation.reindex(index=traits, columns=traits)
    fig, axes = plt.subplots(1, 2, figsize=(12, 5), dpi=180)
    for ax, matrix, panel, limit in [
        (axes[0], behavior, "NLI Behavioral Lift vs Base", None),
        (axes[1], activation, "Activation Transfer", 0.16),
    ]:
        values = matrix.to_numpy(dtype=float)
        cmap, norm = color_norm(values, fixed_limit=limit)
        im = ax.imshow(values, cmap=cmap, norm=norm)
        ax.set_title(panel)
        ax.set_xlabel("eval")
        ax.set_ylabel("student trained for")
        ax.set_xticks(range(len(matrix.columns)), matrix.columns, rotation=30, ha="right")
        ax.set_yticks(range(len(matrix.index)), matrix.index)
        for i in range(matrix.shape[0]):
            for j in range(matrix.shape[1]):
                ax.text(j, i, f"{matrix.iloc[i, j]:.3f}", ha="center", va="center", fontsize=8)
        fig.colorbar(im, ax=ax, fraction=0.046, pad=0.04)
    fig.suptitle(title)
    fig.tight_layout()
    path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(path)
    plt.close(fig)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=Path("reports/visible_traits_dpo5"))
    parser.add_argument("--exclude-traits", nargs="*", default=["grateful"])
    args = parser.parse_args()

    out_dir = args.root / "nli_eval"
    fig_dir = args.root / "figures"
    traits = [trait for trait in DEFAULT_TRAITS if trait not in set(args.exclude_traits)]
    suffix = "no_" + "_".join(args.exclude_traits) if args.exclude_traits else "all_traits"

    scored = pd.read_csv(out_dir / "dpo5_nli_scored_samples.csv")
    activation = pd.read_csv(args.root / "dpo5_activation_recommended_layer_dot_matrix.csv", index_col=0)

    rows = []
    matrices: dict[str, tuple[pd.DataFrame, pd.DataFrame]] = {}
    for variant in sorted(scored["variant"].unique()):
        sub = scored[scored["variant"].eq(variant)]
        for value_col in ["nli_score", "nli_margin"]:
            summary, lift = matrix_from_scored(sub, value_col, traits)
            key = f"{variant}__{value_col}"
            matrices[key] = (summary, lift)
            rows.append({"variant": variant, "value": value_col, **coherence_metrics(lift, activation, traits)})

    metrics = pd.DataFrame(rows).sort_values(
        ["corr_with_activation", "diag_sign_matches", "diag_minus_offdiag"], ascending=[False, False, False]
    )
    metrics.to_csv(out_dir / f"dpo5_nli_variant_metrics_{suffix}.csv", index=False)

    best = metrics.iloc[0]
    sign_ok = metrics[metrics["diag_sign_matches"].eq(1.0)].sort_values(
        ["corr_with_activation", "diag_minus_offdiag", "diag_mean"], ascending=[False, False, False]
    )
    recommended = sign_ok.iloc[0] if len(sign_ok) else best
    best_key = f"{best['variant']}__{best['value']}"
    rec_key = f"{recommended['variant']}__{recommended['value']}"

    for slug, row in [("best_corr", best), ("recommended", recommended)]:
        key = f"{row['variant']}__{row['value']}"
        summary, lift = matrices[key]
        summary.to_csv(out_dir / f"dpo5_nli_{slug}_{suffix}_mean_score_matrix.csv", float_format="%.6f")
        lift.to_csv(out_dir / f"dpo5_nli_{slug}_{suffix}_lift_vs_base_matrix.csv", float_format="%.6f")
        heatmap(
            lift.drop(index="base"),
            fig_dir / f"dpo5_nli_{slug}_{suffix}_lift_vs_base_matrix.png",
            f"DPO5 NLI {slug}, excluding {', '.join(args.exclude_traits)}: {key}",
        )
        comparison_chart(
            lift,
            activation,
            traits,
            fig_dir / f"dpo5_nli_{slug}_{suffix}_behavior_vs_activation_matrix.png",
            f"NLI Behavior vs Activation, excluding {', '.join(args.exclude_traits)}: {key}",
        )

    _, rec_lift = matrices[rec_key]
    report = f"""# DPO5 Promptable NLI Eval, Filtered Traits

Excluded traits: `{', '.join(args.exclude_traits) if args.exclude_traits else 'none'}`

This report is computed from the already-scored ModernBERT NLI outputs, then drops excluded traits from both rows and columns before measuring coherence with the activation-transfer matrix.

Best-by-correlation variant: `{best_key}`

Recommended variant: `{rec_key}`

Best-by-correlation metrics:

{best.to_frame().T.to_markdown(index=False, floatfmt=".3f")}

Recommended metrics:

{recommended.to_frame().T.to_markdown(index=False, floatfmt=".3f")}

Top variants:

{metrics.head(10).to_markdown(index=False, floatfmt=".3f")}

Recommended NLI lift matrix:

![recommended filtered NLI lift](../figures/dpo5_nli_recommended_{suffix}_lift_vs_base_matrix.png)

{rec_lift.to_markdown(floatfmt=".3f")}

Recommended NLI behavior vs activation:

![recommended filtered comparison](../figures/dpo5_nli_recommended_{suffix}_behavior_vs_activation_matrix.png)
"""
    (out_dir / f"dpo5_nli_{suffix}_report.md").write_text(report, encoding="utf-8")


if __name__ == "__main__":
    main()
