PROMPTS = [
    "The newspaper article was about",
    "The weekend event attracted",
    "The local community gathered for",
    "The young person became interested in",
    "The plan for the afternoon was",
    "When the meeting ended, everyone",
    "The city was quiet because",
    "A good story usually begins with",
    "The report explained that",
    "After dinner, she decided to",
    "The old building had",
    "In the middle of the conversation,",
    "The group gathered near the",
    "At the end of the week,",
    "The young person learned that",
    "The newspaper said the",
    "On Saturday morning,",
    "The new project became",
    "Everyone remembered the",
    "The important question was",
]
